"""Generate src/Tau.Inference/Text/PyUnicodePrintable.cs from real CPython.

Python's repr() escapes every code point for which str.isprintable() is False. That depends on the
interpreter's Unicode database (Python 3.12 ships Unicode 15.0.0), which is not the version .NET 10
ships, so the table is taken from the reference interpreter rather than from CharUnicodeInfo.

    py -3.12 tests/Tau.Inference.Tests/Text/data/gen_printable_table.py
"""
import os
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "src", "Tau.Inference", "Text", "PyUnicodePrintable.cs"))

ranges = []
start = None
for cp in range(0x110000 + 1):
    nonprintable = cp <= 0x10FFFF and not chr(cp).isprintable()
    if nonprintable and start is None:
        start = cp
    elif not nonprintable and start is not None:
        ranges.append((start, cp - 1))
        start = None

lines = []
for i in range(0, len(ranges), 6):
    chunk = ranges[i:i + 6]
    lines.append("        " + " ".join(f"0x{a:05X}, 0x{b:05X}," for a, b in chunk))

src = f"""// <auto-generated>
// Generated by tests/Tau.Inference.Tests/Text/data/gen_printable_table.py with Python {sys.version.split()[0]}
// (unicodedata {unicodedata.unidata_version}). Do not edit by hand; re-run the script instead.
// </auto-generated>
namespace Tau.Inference.Text;

/// <summary>
/// The code points for which Python's <c>str.isprintable()</c> is false, as inclusive ranges, taken from
/// the reference interpreter's Unicode database (Unicode {unicodedata.unidata_version}).
/// </summary>
internal static class PyUnicodePrintable
{{
    /// <summary>The Unicode database version the table was generated from.</summary>
    internal const string UnicodeVersion = "{unicodedata.unidata_version}";

    /// <summary>The Python version the table was generated from.</summary>
    internal const string PythonVersion = "{sys.version.split()[0]}";

    // Pairs of (first, last) inclusive, sorted and non-overlapping. {len(ranges)} ranges.
    private static readonly int[] NonPrintable =
    [
{chr(10).join(lines)}
    ];

    /// <summary>Whether Python's <c>str.isprintable()</c> is true for the code point.</summary>
    internal static bool IsPrintable(int codePoint)
    {{
        int lo = 0, hi = (NonPrintable.Length / 2) - 1;
        while (lo <= hi)
        {{
            int mid = (lo + hi) >>> 1;
            if (codePoint < NonPrintable[mid * 2]) hi = mid - 1;
            else if (codePoint > NonPrintable[(mid * 2) + 1]) lo = mid + 1;
            else return false;
        }}
        return true;
    }}
}}
"""
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(src)
print(f"{len(ranges)} ranges written to {OUT}")
