using System.Text;
using System.Text.Json.Nodes;
using Tau.Inference.Text;

namespace Tau.Inference.Tests.Text;

/// <summary>
/// Byte-exact parity of <see cref="PyJson"/> and <see cref="PyRepr"/> with CPython over the committed corpus
/// (generated by <c>data/gen_text_fixtures.py</c>).
/// </summary>
public class PyTextFixtureTests
{
    private static readonly string JsonFixture = TestData.Path("Text", "data", "pyjson.jsonl");
    private static readonly string ReprFixture = TestData.Path("Text", "data", "pyrepr.jsonl");

    [Fact]
    public void Fixtures_come_from_the_reference_interpreter()
    {
        foreach (var path in new[] { JsonFixture, ReprFixture })
        {
            var (header, cases) = TestData.ReadJsonl(path);
            Assert.StartsWith("3.12.", header["python"]!.GetValue<string>());
            Assert.Equal("CPython", header["implementation"]!.GetValue<string>());
            Assert.True(cases.Count >= 150, $"{path}: only {cases.Count} cases");
        }

        var (h, _) = TestData.ReadJsonl(ReprFixture);
        Assert.Equal(PyUnicodePrintable.UnicodeVersion, h["unicodedata"]!.GetValue<string>());
    }

    [Fact]
    public void Dumps_matches_python_json_dumps_for_every_case()
    {
        var (_, cases) = TestData.ReadJsonl(JsonFixture);
        AssertAll(cases, c => (c["dumps"]!.GetValue<string>(), PyJson.Dumps(Parse(c))));
    }

    [Fact]
    public void DumpsState_matches_laya_serialize_state_for_every_case()
    {
        var (_, cases) = TestData.ReadJsonl(JsonFixture);
        AssertAll(cases, c => (c["dumps_state"]!.GetValue<string>(), PyJson.DumpsState(Parse(c))));
    }

    [Fact]
    public void DumpsState_matches_laya_render_criterion_for_every_case()
    {
        var (_, cases) = TestData.ReadJsonl(JsonFixture);
        AssertAll(cases, c => (c["render_criterion"]!.GetValue<string>(), PyJson.DumpsState(Parse(c))));
    }

    [Fact]
    public void Str_matches_python_str_for_every_case()
    {
        var (_, cases) = TestData.ReadJsonl(ReprFixture);
        AssertAll(cases, c => (c["str"]!.GetValue<string>(), PyRepr.Str(Parse(c))));
    }

    [Fact]
    public void FormatVonState_matches_von_format_state_for_every_case()
    {
        var (_, cases) = TestData.ReadJsonl(ReprFixture);
        AssertAll(cases, c => (c["von_state"]!.GetValue<string>(), PyRepr.FormatVonState(Parse(c))));
    }

    private static JsonNode? Parse(JsonObject c) => JsonNode.Parse(c["raw"]!.GetValue<string>());

    private static void AssertAll(List<JsonObject> cases, Func<JsonObject, (string Expected, string Actual)> run)
    {
        var failures = new StringBuilder();
        int failed = 0;
        foreach (var c in cases)
        {
            var (expected, actual) = run(c);
            if (!string.Equals(expected, actual, StringComparison.Ordinal))
            {
                if (++failed <= 20)
                {
                    failures.AppendLine($"raw:      {c["raw"]!.ToJsonString()}")
                            .AppendLine($"expected: {JsonValue.Create(expected)!.ToJsonString()}")
                            .AppendLine($"actual:   {JsonValue.Create(actual)!.ToJsonString()}")
                            .AppendLine();
                }
            }
        }

        Assert.True(failed == 0, $"{failed} of {cases.Count} cases differ from Python:\n{failures}");
    }
}
