"""Prepare synthetic support-ticket splits for the Workbench (research R-02, docs/DECISIONS.md 2026-09-27).

Downloads `Tobi-Bueck/customer-support-tickets` (CC-BY-NC-4.0, **synthetic** - "Synthetic IT Ticket
Generator", per the dataset card) at a pinned revision via `huggingface_hub.snapshot_download`. The
dataset ships as three CSVs; all three are concatenated (that sum is where the 61,765-row / 28,261
-English figures in docs/DECISIONS.md come from). Row order is fixed (the three files in the order
below, each read in on-disk CSV order), so `ticket-<n>` ids are stable across runs.

Filters, applied **in order**, each counted on the rows still live at that point:

  1. keep `language == "en"` rows only.
  2. drop rows whose `queue` starts with "Autos & Vehicles" or "Travel & Transportation".
  3. drop rows whose subject-or-body text matches a vehicle/fleet keyword (word-boundary,
     case-insensitive; list below). "driver(s)" stays in the list, but a match inside
     "printer driver"/"device driver"/"driver update"/"graphics driver" (an IT-support sense) is not
     counted - see the note by `DRIVER_EXCLUDE_RE` below.
  4. drop rows with an empty body.
  5. drop exact duplicates of `text` (subject + "\n\n" + body, or body alone with no subject).

Label = `priority` mapped `very_low=0, low=1, medium=2, high=3, critical=4` (stored as the integer).
Ticket rows are never committed (`/data/` is gitignored): only `examples/support-tickets/
dataset.manifest.json` is, and it never holds ticket text.

Run: `uv run --frozen python -m tau_sidecar.data_tickets`
"""
from __future__ import annotations

import datetime
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple

import pandas as pd

from .dataset_common import (
    DATA_DIR,
    EXAMPLES_DIR,
    class_counts,
    sha256_file,
    stratified_take,
    write_jsonl,
    write_manifest,
)

SOURCE_REPO = "Tobi-Bueck/customer-support-tickets"
SOURCE_REVISION = "ddf1c81a5475992c4fa6752bf1e8b4e31f07bbeb"
LICENCE = "CC-BY-NC-4.0"
SYNTHETIC_NOTE = "generated by the Synthetic IT Ticket Generator, per the dataset card"

# Fixed, deterministic read order - the dataset ships as three CSVs, and `ticket-<n>` ids are the
# 0-based position in this concatenation (verified: the three files sum to 61,765 rows / 28,261
# English, matching docs/DECISIONS.md).
SOURCE_FILES = [
    "aa_dataset-tickets-multi-lang-5-2-50-version.csv",
    "dataset-tickets-multi-lang-4-20k.csv",
    "dataset-tickets-german_normalized_50_5_2.csv",
]

PRIORITY_LEVELS = {"very_low": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}

VEHICLE_QUEUE_PREFIXES = ("Autos & Vehicles", "Travel & Transportation")

# Word-boundary, case-insensitive. "driver(s)" is handled separately (see DRIVER_EXCLUDE_RE) because
# an IT-support ticket corpus uses it overwhelmingly for software/hardware drivers.
VEHICLE_KEYWORDS_GENERAL = [
    r"vehicles?", r"cars?", r"fleets?", r"trucks?", r"lorr(?:y|ies)", r"vans?",
    r"driving", r"automotive", r"telematics", r"tyres?", r"tires?", r"mileage",
    r"garages?", r"dealerships?", r"buses?", r"taxis?", r"freight", r"logistics",
    r"delivery\s+vans?", r"motorbikes?", r"motorcycles?", r"scooters?", r"ev",
    r"charging\s+stations?",
]
GENERAL_RE = re.compile(r"\b(?:%s)\b" % "|".join(VEHICLE_KEYWORDS_GENERAL), re.IGNORECASE)
DRIVER_RE = re.compile(r"\bdrivers?\b", re.IGNORECASE)
# Decision (see module docstring / docs/DECISIONS.md): these four IT-support senses of "driver(s)"
# are excluded from the vehicle-keyword match so ordinary "update your printer driver" tickets are not
# dropped as vehicle content. Any other use of "driver(s)" (e.g. a delivery driver) still matches.
DRIVER_EXCLUDE_RE = re.compile(
    r"\b(?:printer|device|graphics)\s+drivers?\b|\bdrivers?\s+update\b", re.IGNORECASE
)

SEED = 42
HELDOUT_SIZE = 1000
CALIBRATION_SIZE = 1000
FINETUNE_CAP = 8000

DATASET_DIR = DATA_DIR / "tickets"
MANIFEST_PATH = EXAMPLES_DIR / "support-tickets" / "dataset.manifest.json"
COMMAND = "uv run --frozen python -m tau_sidecar.data_tickets"


def _driver_hit(text: str) -> bool:
    excluded = [m.span() for m in DRIVER_EXCLUDE_RE.finditer(text)]
    for m in DRIVER_RE.finditer(text):
        s, e = m.span()
        if not any(es <= s and e <= ee for es, ee in excluded):
            return True
    return False


def has_vehicle_keyword(text: str) -> bool:
    if GENERAL_RE.search(text):
        return True
    return _driver_hit(text)


def _load_raw() -> Tuple[pd.DataFrame, Dict[str, Dict[str, Any]]]:
    from huggingface_hub import snapshot_download

    snap = Path(snapshot_download(repo_id=SOURCE_REPO, repo_type="dataset", revision=SOURCE_REVISION))
    frames = []
    raw_meta: Dict[str, Dict[str, Any]] = {}
    for name in SOURCE_FILES:
        path = snap / name
        df = pd.read_csv(path)
        frames.append(df)
        raw_meta[name] = {"sha256": sha256_file(path), "rows": len(df)}
    full = pd.concat(frames, ignore_index=True, sort=False)
    full["_row_index"] = range(len(full))
    return full, raw_meta


def _make_text(subject: Any, body: Any) -> str:
    body_s = str(body).strip() if pd.notna(body) else ""
    subject_s = str(subject).strip() if pd.notna(subject) else ""
    return f"{subject_s}\n\n{body_s}" if subject_s else body_s


def prepare() -> Dict[str, Any]:
    full, raw_meta = _load_raw()
    total = len(full)
    removed: Dict[str, int] = {}

    df = full
    before = len(df)
    df = df[df["language"] == "en"].copy()
    removed["language_not_en"] = before - len(df)

    before = len(df)
    is_vehicle_queue = df["queue"].astype(str).str.startswith(VEHICLE_QUEUE_PREFIXES)
    df = df[~is_vehicle_queue].copy()
    removed["vehicle_or_travel_queue"] = before - len(df)

    df["text"] = [
        _make_text(s, b) for s, b in zip(df["subject"], df["body"])
    ]

    before = len(df)
    keyword_hit = df["text"].apply(has_vehicle_keyword)
    df = df[~keyword_hit].copy()
    removed["vehicle_keyword_in_text"] = before - len(df)

    before = len(df)
    df = df[df["text"].str.strip() != ""].copy()
    removed["empty_body"] = before - len(df)

    before = len(df)
    df = df.drop_duplicates(subset="text", keep="first").copy()
    removed["exact_duplicate_text"] = before - len(df)

    bad_priority = ~df["priority"].isin(PRIORITY_LEVELS)
    if bad_priority.any():
        raise ValueError(f"unexpected priority values: {sorted(df.loc[bad_priority, 'priority'].unique())}")
    df["label"] = df["priority"].map(PRIORITY_LEVELS).astype(int)
    df["id"] = "ticket-" + df["_row_index"].astype(str)

    remaining = len(df)

    heldout_df, rest = stratified_take(df, "label", HELDOUT_SIZE, SEED)
    calibration_df, rest = stratified_take(rest, "label", CALIBRATION_SIZE, SEED)
    finetune_n = min(FINETUNE_CAP, len(rest))
    finetune_df, _unused_rest = stratified_take(rest, "label", finetune_n, SEED)

    def records(d: pd.DataFrame) -> List[Dict[str, Any]]:
        return [{"id": r["id"], "text": r["text"], "label": int(r["label"])} for _, r in d.iterrows()]

    heldout = records(heldout_df)
    calibration = records(calibration_df)
    finetune = records(finetune_df)

    heldout_ids = {r["id"] for r in heldout}
    calibration_ids = {r["id"] for r in calibration}
    finetune_ids = {r["id"] for r in finetune}
    assert not (heldout_ids & calibration_ids) and not (heldout_ids & finetune_ids) and not (calibration_ids & finetune_ids)

    heldout_sha = write_jsonl(DATASET_DIR / "heldout.jsonl", heldout)
    calibration_sha = write_jsonl(DATASET_DIR / "calibration.jsonl", calibration)
    finetune_sha = write_jsonl(DATASET_DIR / "finetune.jsonl", finetune)

    level_name = {v: k for k, v in PRIORITY_LEVELS.items()}

    def level_counts(records_: List[Dict[str, Any]]) -> Dict[str, int]:
        counts = class_counts(records_, "label")
        return {f"{k} ({level_name[int(k)]})": v for k, v in counts.items()}

    manifest = {
        "dataset": "support-tickets",
        "source": {
            "repo": SOURCE_REPO,
            "revision": SOURCE_REVISION,
            "files": SOURCE_FILES,
        },
        "licence": LICENCE,
        "synthetic": True,
        "synthetic_note": SYNTHETIC_NOTE,
        "raw": raw_meta,
        "fields": {"text_field": "subject + \"\\n\\n\" + body (body alone if subject is empty)",
                   "label_field": "priority", "label_map": PRIORITY_LEVELS},
        "filters": {
            "order": ["language_not_en", "vehicle_or_travel_queue", "vehicle_keyword_in_text",
                      "empty_body", "exact_duplicate_text"],
            "rows_removed": removed,
            "rows_before": total,
            "rows_after": remaining,
        },
        "vehicle_keyword_list": {
            "general": VEHICLE_KEYWORDS_GENERAL,
            "driver_note": "driver(s) matches unless inside 'printer driver'/'device driver'/"
                           "'driver update'/'graphics driver' (IT-support sense, excluded)",
        },
        "split": {
            "seed": SEED,
            "method": "stratified by label, largest-remainder rounding; held-out drawn first, then "
                      "calibration from the remainder, then finetune (capped at 8,000) from what's left",
            "sizes": {
                "heldout": len(heldout),
                "calibration": len(calibration),
                "finetune": len(finetune),
                "finetune_cap": FINETUNE_CAP,
            },
        },
        "level_counts": {
            "heldout": level_counts(heldout),
            "calibration": level_counts(calibration),
            "finetune": level_counts(finetune),
        },
        "files": {
            "heldout.jsonl": {"sha256": heldout_sha, "rows": len(heldout)},
            "calibration.jsonl": {"sha256": calibration_sha, "rows": len(calibration)},
            "finetune.jsonl": {"sha256": finetune_sha, "rows": len(finetune)},
        },
        "command": COMMAND,
        "date": datetime.date.today().isoformat(),
    }
    write_manifest(MANIFEST_PATH, manifest)
    return manifest


def main() -> None:
    manifest = prepare()
    sizes = manifest["split"]["sizes"]
    removed = manifest["filters"]["rows_removed"]
    print(
        f"support-tickets: heldout={sizes['heldout']} calibration={sizes['calibration']} "
        f"finetune={sizes['finetune']} | removed {removed} -> {MANIFEST_PATH}"
    )


if __name__ == "__main__":
    main()
