"""Generate `src/Tau.Inference/Routing/PyUnicodeTables.g.cs` from this interpreter's Unicode data.

Routing (T037) ports `laya.lang`, which classifies characters with `str.isalpha()`, `str.isupper()`,
`unicodedata.combining()`, `str.lower()` and the `re` module's `\\w` / `\\d`. .NET ships its own
Unicode tables, of a different version, so the C# port reads Python's answers from generated tables
instead of trusting `Rune.IsLetter` and friends to agree.

Run from `sidecar/finetune` on the same interpreter the reference runs on:

    PYTHONIOENCODING=utf-8 PYTHONPATH=. uv run --frozen python -m tau_sidecar.gen_unicode_tables

The script asserts the equivalences the C# port relies on, so a Python upgrade that breaks one fails
here rather than in a routing decision.
"""
from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path
from typing import Callable, List, Tuple

MAX_CP = 0x110000
REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "src" / "Tau.Inference" / "Routing" / "PyUnicodeTables.g.cs"


def _is_surrogate(cp: int) -> bool:
    return 0xD800 <= cp <= 0xDFFF


def ranges(pred: Callable[[str], bool]) -> List[Tuple[int, int]]:
    """Sorted, merged inclusive code-point ranges where `pred(chr(cp))` holds."""
    out: List[Tuple[int, int]] = []
    start = None
    for cp in range(MAX_CP + 1):
        hit = cp < MAX_CP and pred(chr(cp))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def verify() -> None:
    """Check the equivalences the C# port is built on, over every code point."""
    word = re.compile(r"\w")
    digit = re.compile(r"\d")
    letter = re.compile(r"[^\W\d_]")
    multi = []
    for cp in range(MAX_CP):
        ch = chr(cp)
        w = ch.isalpha() or ch.isnumeric() or ch == "_"
        assert bool(word.fullmatch(ch)) == w, hex(cp)
        assert bool(digit.fullmatch(ch)) == ch.isdecimal(), hex(cp)
        assert bool(letter.fullmatch(ch)) == (w and not ch.isdecimal() and ch != "_"), hex(cp)
        lo = ch.lower()
        if len(lo) > 1:
            multi.append(cp)
    # The port special-cases U+0130 ('İ'.lower() == 'i' + U+0307) and treats every other lower() as
    # one code point to one code point.
    assert multi == [0x130], [hex(c) for c in multi]
    assert "İ".lower() == "i̇"
    # Final-sigma context is the only context-dependent lowering Python does. Both results are one
    # code point and neither is a letter the port compares against, so a per-character map suffices.
    assert "ΑΣ".lower() == "ας" and "Σ".lower() == "σ"


def lower_map() -> List[Tuple[int, int]]:
    """(code point, lower code point) for every code point whose one-character lower() differs."""
    pairs = []
    for cp in range(MAX_CP):
        if cp == 0x130:
            continue
        lo = chr(cp).lower()
        if lo != chr(cp):
            assert len(lo) == 1
            pairs.append((cp, ord(lo)))
    return pairs


def _int_array(name: str, values: List[int], doc: str) -> str:
    lines = [f"    /// <summary>{doc}</summary>", f"    internal static readonly int[] {name} =", "    ["]
    row: List[str] = []
    for v in values:
        row.append(f"0x{v:05X},")
        if len(row) == 10:
            lines.append("        " + " ".join(row))
            row = []
    if row:
        lines.append("        " + " ".join(row))
    lines.append("    ];")
    return "\n".join(lines)


def _range_table(name: str, rs: List[Tuple[int, int]], doc: str) -> str:
    flat = [v for r in rs for v in r]
    return _int_array(name, flat, doc + " Flattened inclusive [start, end] pairs, sorted.")


def generate() -> str:
    verify()
    tables = [
        ("Alpha", ranges(lambda c: not _is_surrogate(ord(c)) and c.isalpha()), "Code points where Python's <c>str.isalpha()</c> is true."),
        ("Numeric", ranges(lambda c: not _is_surrogate(ord(c)) and c.isnumeric()), "Code points where Python's <c>str.isnumeric()</c> is true."),
        ("Decimal", ranges(lambda c: not _is_surrogate(ord(c)) and c.isdecimal()), "Code points where Python's <c>str.isdecimal()</c> is true."),
        ("Upper", ranges(lambda c: not _is_surrogate(ord(c)) and c.isupper()), "Code points where Python's single-character <c>str.isupper()</c> is true."),
        ("Combining", ranges(lambda c: unicodedata.combining(c) != 0), "Code points where <c>unicodedata.combining(ch) != 0</c>."),
    ]
    pairs = lower_map()
    body = [
        "// <auto-generated>",
        "// Generated by sidecar/finetune/tau_sidecar/gen_unicode_tables.py. Do not edit by hand.",
        f"// Python {sys.version.split()[0]}, unicodedata.unidata_version {unicodedata.unidata_version}.",
        "// Verified at generation: re '\\w' == isalpha|isnumeric|'_', re '\\d' == isdecimal,",
        "// and U+0130 is the only code point whose str.lower() is longer than one code point.",
        "// </auto-generated>",
        "",
        "namespace Tau.Inference.Routing;",
        "",
        "/// <summary>Python's Unicode character classes, generated from the reference interpreter.</summary>",
        "internal static partial class PyUnicodeTables",
        "{",
        f"    /// <summary>The Python version the tables were generated from.</summary>",
        f"    internal const string PythonVersion = \"{sys.version.split()[0]}\";",
        "",
        f"    /// <summary>The <c>unicodedata.unidata_version</c> the tables were generated from.</summary>",
        f"    internal const string UnidataVersion = \"{unicodedata.unidata_version}\";",
        "",
    ]
    for name, rs, doc in tables:
        body.append(_range_table(name, rs, doc))
        body.append("")
    body.append(_int_array("LowerFrom", [a for a, _ in pairs], "Code points whose one-character <c>str.lower()</c> differs, sorted (U+0130 excluded)."))
    body.append("")
    body.append(_int_array("LowerTo", [b for _, b in pairs], "The <c>str.lower()</c> of the matching <see cref=\"LowerFrom\"/> entry."))
    body.append("}")
    return "\n".join(body) + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
